### ISSUE TITLE
Code Coverage

### ISSUE THREAD

**Issue by froid1911** [LimeChain/matchstick#140]
As a user I want to get a code coverage report after I run the tests.

- Calculate Code Coverage
- Generate Code Coverage Report 

EDIT
Estimate: 1-2 weeks

**Comment by axiomatic-aardvark** [comment]
Hey @froid1911, thanks so much for raising that with us! It's a pretty good idea and we will definitely consider adding that feature. I just want to ask - when you say "calculate code coverage" does that mean check how many (as a percentage) datasources and handlers in those datasources have been tested or do you have something else in mind?

**Comment by froid1911** [comment]
exactly. It would be great to know how much code is covered through the tests for different data sources with different handlers and branches. I think jest code coverage report is a good example:

![image](https://user-images.githubusercontent.com/1188574/129212936-6a8c5e8a-2edb-4e92-888c-c6f6e5b85a25.png)

**Comment by axiomatic-aardvark** [comment]
Awesome 💯  I think that'll be a very useful feature, and also it can be done fairly easily. Tossing it in our to-dos.
