### ISSUE TITLE
Dev test Matchstick on Windows

### ISSUE THREAD

**Issue by axiomatic-aardvark** [LimeChain/matchstick#154]
Run the [demo subgraph](https://github.com/LimeChain/demo-subgraph) examples in a Windows environment with the Windows release binary.

Estimate: 1 day

**Comment by Elyx0** [comment]
I did just that, windows 10, node v14.17.1 
```
yarn install
yarn test
```
all test pass

**Comment by axiomatic-aardvark** [comment]
Awesome, thank you!

**Comment by Elyx0** [comment]
Actually the `./matchstick Gravity` in yarn doesnt pass. I had to run `./matchstick` myself from windows git bash (mingw64). I tried copying the executable to `/node_modules/.bin` but even that doesn't recognize the `matchstick` command in npm.
```
'.\matchstick' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by Elyx0** [comment]
Trick with nodemon as dev dep: `    "watch:GenericWalletManager": "nodemon --exec yarn test ./src "

**Comment by axiomatic-aardvark** [comment]
That's a neat work-around! We should add that to the docs
