### ISSUE TITLE
Codegen tool to create event-, call, transaction-objects from actual data from Etherscan

### ISSUE THREAD

**Issue by schmidsi** [LimeChain/matchstick#196]
Today I invested a lot of time to create these `ethereum.Call`, `ethereum.Event` objects from actual data as I found them on Etherscan. In my opinion, a typical use-case for matchstick would be:

- The developer knows already some transactionHashes who they are interested in, for example: https://etherscan.io/tx/0xaeef5ea449f5b37a2ee28179f5d782c0d708dac562c08cc1a3af113bf6807148
- Adding these transactionHashes to a special codegen config file
- Running the test-codegen then goes to Etherscan (or any other block explorer) and gets these transactions and creates the other objects: `ethereum.Block`, `ethereum.Call`, `ethereum.Event`, `ethereum.Transaction` and so on to be ready to be used in the tests.

This could be a tool by its own or included in this library. Not sure where to put it.

**Comment by bsamuels453** [comment]
At Yearn we're using a fixture generator for mocking chain state for tests. Might work nicely with the block/call/event/txn generator proposed here; https://github.com/yearn/yearn-vaults-v2-subgraph/tree/main/tests
