### ISSUE TITLE
fix `logStore()` not logging anything when the test passes successfully

### ISSUE THREAD

**Issue by georg-getz** [LimeChain/matchstick#245]
Estimate: 3h

**Comment by dimitrovmaksim** [comment]
I found the issue, basically logStore() and failed test logs were accumulated in the same variable, so when I moved that variable to be displayed on the bottom only when the test has failed it also removed the logging of the store.

**Comment by dimitrovmaksim** [comment]
So this happened here https://github.com/LimeChain/matchstick/commit/dcd635a8f616002e883eb3ec94daa3602c8647bc,   we could probably bring back
```
if !logs.is_empty() {
     println!("{}", logs);
}
```
and add `&& passed` to the condition.
