### ISSUE TITLE
Internal error during compilation: %1 is not a valid Win32 application. (os error 193)

### ISSUE THREAD

**Issue by darkspring1** [LimeChain/matchstick#271]
![image](https://user-images.githubusercontent.com/6180095/148648703-564b4199-8865-4af0-946b-50ef15cc3423.png)

**Comment by darkspring1** [comment]
I try to run tests from demo project (https://github.com/LimeChain/demo-subgraph) and catch error (See screenshot above)

My package.json content:
{
  "name": "demo",
  "version": "0.1.0",
  "repository": "https://github.com/LimeChain/demo-subgraph",
  "license": "MIT",
  "scripts": {
    "codegen": "graph codegen",
    "build": "graph build",
    "create-local": "graph create demo --node http://127.0.0.1:8020",
    "deploy-local": "graph deploy demo --ipfs http://localhost:5001 --node http://127.0.0.1:8020",
    "test": "graph test gravity",
    "coverage": "graph test -- -c"
  },
  "dependencies": {
    "@graphprotocol/graph-cli": "^0.25.1",
    "@graphprotocol/graph-ts": "^0.24.1",
    "matchstick-as": "^0.2.3"
  }
}

**Comment by dimitrovmaksim** [comment]
Could you try downloading `binary-windows` from the releseas to the `demo-subgraph` folder, add the `.exe` extension to the name and run `./binary-windows.exe`.

**Comment by darkspring1** [comment]
The same error
![image](https://user-images.githubusercontent.com/6180095/148689725-3be2696f-59cc-4154-bb3b-7ba5bc35f35a.png)

**Comment by dimitrovmaksim** [comment]
Thank you! You could use the docker solution described here https://github.com/LimeChain/matchstick#docker- while we investigate the issue

**Comment by dimitrovmaksim** [comment]
After some considerations we decided to drop support for the windows binary for now. Meanwhile you can use the docker solution mentioned in the previous comment. I will close this Issue for now.
