### ISSUE TITLE
Coverage flag not working

### ISSUE THREAD

**Issue by ghardin1314** [LimeChain/matchstick#274]
The coverage flag update in 0.2.3 does not seem to be working. I get the following error when using `-c`

![image](https://user-images.githubusercontent.com/54160127/149050799-5876aea0-e4ea-43c6-a6b0-48b7c08f7285.png)

This is the same if I try to run naively on Linux or in a dockerfile similar to the `subgraph-demo` setup

config:
```
"@graphprotocol/graph-cli": "0.25.1",
"@graphprotocol/graph-ts": "0.24.1",
"matchstick-as": "0.2.3",
```

**Comment by dimitrovmaksim** [comment]
Could you try deleting `node_modules` and `package-lock.json`, then run `npm install` again.

**Comment by dimitrovmaksim** [comment]
So, currently there is a small limitation, in order for the coverage to work, your test suite name should match the mapping name, for example in the demo-subgraph, the mappings file name is [gravity.ts](https://github.com/LimeChain/demo-subgraph/blob/main/subgraph.yaml#L31), and the tests are located in './tests/gravity', which creates a test suite named `gravity`.

**Comment by ghardin1314** [comment]
Ah, so because our files are named <DATA_SOURCE>.mapping.ts this is causing the issue?

Does folder structure also matter? Until #275 is closed we have to use one test suite called `subgraph` to separate our mapping tests from our contracts tests

**Comment by dimitrovmaksim** [comment]
Could you try running the coverage with version `0.2.4-alpha` and tell me if it works?
