### ISSUE TITLE
Contract.bind(datasource.address()) fails

### ISSUE THREAD

**Issue by 0xSkly** [LimeChain/matchstick#297]
When trying to interact with the datasource contract bound via `Contract.bind(datasource.address())` it fails with

`thread 'main' panicked at 'source slice length (42) does not match destination slice length (20)'`

Printing  `datasource.address().toHex()` results in `0x307830303030303030303030303030303030303030303030303030303030303030303030303030303031` which might be the issue, not sure tbh. `datasource.address().toString()` prints the expected zero address.

it works when i do this little hack `Contract.bind(
    Address.fromString(dataSource.address().toString())
  )`

Thanks for the great work!

**Comment by dimitrovmaksim** [comment]
Should be fixed by https://github.com/LimeChain/matchstick/pull/307 and the fix will be included in the next version of matchstick

**Comment by dimitrovmaksim** [comment]
v0.4.1 containing the fix is released

**Comment by dimitrovmaksim** [comment]
Closing this Issue as the issue should be fixed
