### ISSUE TITLE
Error on building matchstick on Docker Windows

### ISSUE THREAD

**Issue by wctse** [LimeChain/matchstick#306]
Hi everyone. I am new to Docker so apologize in advance for any newbie errors.

I am installing matchstick in a file through Docker on Windows by running `docker build -t matchstick .`. It runs until step 9/15 and the follow error occurs:
```
------
=> ERROR [ 9/15] RUN curl -OL https://github.com/LimeChain/matchstick/releases/download/<MATCHSTICK_VERSION>/bin  1.1s

> [ 9/15] RUN curl -OL https://github.com/LimeChain/matchstick/releases/download/<MATCHSTICK_VERSION>/binary-linux-20:
#12 0.848 /bin/sh: 1: cannot open MATCHSTICK_VERSION: No such file
------
executor failed running [/bin/sh -c curl -OL https://github.com/LimeChain/matchstick/releases/download/<MATCHSTICK_VERSION>/binary-linux-20]: exit code: 2
```

Can you help me solve this issue? Thank you!

**Comment by dimitrovmaksim** [comment]
You should replace <MATCHSTICK_VERSION> [here](https://github.com/LimeChain/demo-subgraph/blob/main/Dockerfile#L15) with an actual version, for example 0.4.0 , e.g. `RUN curl -OL https://github.com/LimeChain/matchstick/releases/download/0.4.0/binary-linux-20`

**Comment by wctse** [comment]
Ah! My bad. Thank you!
