### ISSUE TITLE
"SyntaxError: Unexpected token =" when running "docker build -t matchstick ."

### ISSUE THREAD

**Issue by mmartinmo** [LimeChain/matchstick#311]
Hi,

when I run `docker build -t matchstick .` I get following error

```
 => ERROR [14/15] RUN npm run codegen                                                                                                6.9s
------
 > [14/15] RUN npm run codegen:
#18 1.619
#18 1.619 > nft-share-platform-ropsten@ codegen /matchstick
#18 1.619 > graph codegen
#18 1.619
#18 6.794 /matchstick/node_modules/@graphprotocol/graph-cli/src/codegen/schema.js:9
#18 6.794   static BYTES = Symbol("Bytes")
#18 6.794                ^
#18 6.794
#18 6.794 SyntaxError: Unexpected token =
#18 6.794     at Module._compile (internal/modules/cjs/loader.js:723:23)
#18 6.794     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
#18 6.794     at Module.load (internal/modules/cjs/loader.js:653:32)
#18 6.794     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
#18 6.794     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
#18 6.794     at Module.require (internal/modules/cjs/loader.js:692:17)
#18 6.794     at require (internal/modules/cjs/helpers.js:25:18)
#18 6.794     at Object.<anonymous> (/matchstick/node_modules/@graphprotocol/graph-cli/src/schema.js:5:27)
#18 6.794     at Module._compile (internal/modules/cjs/loader.js:778:30)
#18 6.794     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
#18 6.801 npm ERR! code ELIFECYCLE
#18 6.801 npm ERR! errno 1
#18 6.802 npm ERR! nft-share-platform-ropsten@ codegen: `graph codegen`
#18 6.803 npm ERR! Exit status 1
#18 6.803 npm ERR!
#18 6.803 npm ERR! Failed at the nft-share-platform-ropsten@ codegen script.
#18 6.804 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#18 6.822
#18 6.822 npm ERR! A complete log of this run can be found in:
#18 6.822 npm ERR!     /root/.npm/_logs/2022-03-16T14_58_53_712Z-debug.log
------
executor failed running [/bin/sh -c npm run codegen]: exit code: 1
```

This is my Dockerfile

```FROM ubuntu:20.04

ARG BUILDPLATFORM=linux/x86_64

ENV ARGS=""

RUN apt update
RUN apt install -y nodejs
RUN apt install -y npm
RUN apt install -y git
RUN apt install -y postgresql
RUN apt install -y curl
RUN apt install -y cmake

RUN curl -OL https://github.com/LimeChain/matchstick/releases/download/0.3.0/binary-linux-20
RUN chmod a+x binary-linux-20

RUN mkdir matchstick
WORKDIR /matchstick

COPY ../ .

RUN npm run codegen
RUN npm run build

CMD ../binary-linux-20 ${ARGS}
```

When I run `npm run codegen` in my subgraph project it finishes without error. 

Host PC is Windows 11. Any ideas what went wrong?

**Comment by dimitrovmaksim** [comment]
Hey, what were the versions before that?

**Comment by mmartinmo** [comment]
Before it was
```
 "@graphprotocol/graph-cli": "0.28.0",
 "@graphprotocol/graph-ts": "0.26.0"
```
Is documented somewhere which version of matchstick requires which version of graph?

**Comment by glinda93** [comment]
I also have this issue.

Also types do not match between `@graphprotocol` and `matchstick-as` in the above versions.

**Comment by dimitrovmaksim** [comment]
I'll have to investigate

**Comment by dimitrovmaksim** [comment]
Btw if you're using `docker run -it --rm --mount type=bind,source=<absolute/path/to/project>,target=/matchstick matchstick` to run the docker container, I think it's safe to remove the `codegen` and `build` commands from the dockerfile

**Comment by dimitrovmaksim** [comment]
Can you try this Dockerfile?
```
FROM ubuntu:20.04

ARG BUILDPLATFORM=linux/x86_64
ARG DEBIAN_FRONTEND=noninteractive

ENV ARGS=""

RUN apt update \
  && apt install -y sudo curl postgresql \
  && curl -fsSL https://deb.nodesource.com/setup_16.x | sudo bash - \
  && sudo apt install -y nodejs \
  && curl -OL https://github.com/LimeChain/matchstick/releases/download/0.4.1/binary-linux-20 \
  && chmod a+x binary-linux-20

RUN mkdir matchstick
WORKDIR /matchstick

COPY ../ .

RUN npm run codegen
RUN npm run build

CMD ../binary-linux-20 ${ARGS}
```

**Comment by mmartinmo** [comment]
Thanks for the mount command hint, that made the test run much faster.

Regarding the dockerfile - with which graph versions should I try it?

Btw the error from the original post was initially not happening when doing codegen outside of the docker, but after I ran again the install command ( `yarn install`?) it was also happening both locally and inside docker. So most likely it is not a matchstick related issue?

**Comment by dimitrovmaksim** [comment]
The nodejs version installed in the docker is old, and think this is what is causing the issue

**Comment by dimitrovmaksim** [comment]
> Thanks for the mount command hint, that made the test run much faster.
> Regarding the dockerfile - with which graph versions should I try it?

I think from graph-cli 0.25.1 the docker is incorporated in the `graph test` command with the `-d` option. From 0.27.0 it downloads the dockerfile from the demo-subgraph repo. But the Dockerfile is not perfect yet.

> Btw the error from the original post was initially not happening when doing codegen outside of the docker, but after I ran again the install command ( `yarn install`?) it was also happening both locally and inside docker. So most likely it is not a matchstick related issue?

```
"@graphprotocol/graph-cli": "0.28.1",
"@graphprotocol/graph-ts": "0.26.0",
```
Works locally for me(macOS) and also with the new Dockerfile with nodejs v16

**Comment by mmartinmo** [comment]
Thank you for the explanation! The issue can be closed from my side.
