### ISSUE TITLE
Where should I place the matchstick binary?

### ISSUE THREAD

**Issue by 0xbe1** [LimeChain/matchstick#313]
When I run `graph test`, I am supposed to be downloading the binary to a certain location, however the network of my dev laptop is not great 🤷 

```
$ graph test -- -c
Downloading release from https://github.com/LimeChain/matchstick/releases/download/0.4.0/binary-macos-10.15
Error fetching release: read ECONNRESET
```

But I am able to download the binary by clicking into the link https://github.com/LimeChain/matchstick/releases/download/0.4.0/binary-macos-10.15.

However I am not clear where should I locate the binary in order to proceed. Any help?

**Comment by dimitrovmaksim** [comment]
Depend where graph-cli is installed.
For globally installed graph-cli:
 - If you use `nvm`:  `/Users/<user>/.nvm/versions/node/<node_version>/lib/node_modules/@graphprotocol/graph-cli/node_modules/binary-install-raw/bin/<matchstick_version>/`

For the locally installed graph-cli: `/node_modules/binary-install-raw/bin/<matchstick_version>`
