### ISSUE TITLE
TypeScript error: function parameters don't support more than on type

### ISSUE THREAD

**Issue by PierrickGT** [LimeChain/matchstick#317]
Hi,

I have the following helper function that I use to set a value on an entity:
```
export const setTicket = (entity: Account | Delegation, ticket: Address): void => {
  // If just created set ticket field
  if (entity.ticket == null) {
    entity.ticket = ticket.toHexString();
  }
};
```

When running tests, I get the following error:
```
ERROR TS1005: 'null' expected.

 export const setTicketOnDelegation = (entity: Account | Delegation, ticket: Address): void => {
```

So instead of the `Delegation` type, it expects `null` and I can't have more than one type for the `entity` parameter.
Is there any way to avoid this error? Would be great to not have to create a function per entity.

**Comment by dimitrovmaksim** [comment]
You can try using a generic type:
```
export function setTicket<T>(entity: T, ticket: Address): void {
  // If just created set ticket field
  if (entity.ticket == null) {
    entity.ticket = ticket.toHexString();
  }
};
```

**Comment by PierrickGT** [comment]
> You can try using a generic type:
> 
> ```
> export function setTicket<T>(entity: T, ticket: Address): void {
>   // If just created set ticket field
>   if (entity.ticket == null) {
>     entity.ticket = ticket.toHexString();
>   }
> };
> ```

Ah yes it works, thank you!
