### ISSUE TITLE
multiple newMockEvent(), same reference?

### ISSUE THREAD

**Issue by OlaStenberg** [LimeChain/matchstick#319]
When I create two mock events with `newMockEvent()` and change e.g. the block timestamp, it changes on both of them.
See screenshots below:

![image](https://user-images.githubusercontent.com/29061789/159927197-ad5f0a90-6be3-4ccb-8bbc-dd2a0ec5faad.png)
![image](https://user-images.githubusercontent.com/29061789/159928504-8e825ec8-8160-433a-b801-909c404c83f6.png)
![image](https://user-images.githubusercontent.com/29061789/159928589-6c3350b6-c68f-4dbd-a80b-8448b51b6ea9.png)

I expect the `auctionEvent.block.timestamp` to still be 1 after changing `bidEvent.event.timestamp`, seems it doesn't matter that I've created two separate mocks, seems to reference to the value

My current workaround is to set the second events timestamp after the first one has been used, but I'd prefer to do all my setup in the beginning of the test

**Comment by georg-getz** [comment]
Thanks for the bug report. I just released a new matchstick-as version (0.4.2) that fixes this problem.

Note 1: if you just update the `package.json` file to point to version `0.4.2` of matchstick-as but have no changes in the test file you will need to run the following command the first time: `graph test -- -r` to force the test wasm binaries to recompile
Note 2: I see that you are manually assigning every field from the mock event to the event of the type you need, that can be done more easily using `changetype` like in [here](https://github.com/LimeChain/demo-subgraph/blob/main/tests/gravity/gravity.test.ts#L151)

**Comment by OlaStenberg** [comment]
> Note 2: I see that you are manually assigning every field from the mock event to the event of the type you need, that can be done more easily using `changetype` like in [here](https://github.com/LimeChain/demo-subgraph/blob/main/tests/gravity/gravity.test.ts#L151)

Thanks, yeah I've used that in other subgraphs, but on this one I am working currently I was seeing syntax error, so I just did a quick workaround! 

Thanks for the quick fix :-)
