### ISSUE TITLE
Mocking An event, with no ID as a parameter in the event.

### ISSUE THREAD

**Issue by shreyas3336** [LimeChain/matchstick#322]
I'm trying to mock up an Event with definition as 
`Info(name:string, creator:address, value:uint256)`

Entity Definition 

> type Project @entity {
>   id: ID!
>   creator: Bytes!
>   value: BigInt!
>   name: String!
> }

The ID for the entity is generated using the function

> export function generateID(_name: string, _creator: string): string {
>   return _name.concat("-CREATES-").concat(_creator);
> }

I'm not able to load this Entity into the matchStick framework using `Project.load(generateID(name,creator)`, nor am I able to use `asset.fieldEquals` to check the sanity of the logic.

**Comment by georg-getz** [comment]
Issue resolved in discord
