### ISSUE TITLE
Cannot make it work on Mac

### ISSUE THREAD

**Issue by HetmanJones** [LimeChain/matchstick#324]
Hey hi, not sure where to ask for help. 

I'm basically trying to run Matchstick, which by the way amazing project.
But I'm getting the following

<img width="1047" alt="Screenshot 2022-04-08 at 20 51 36" src="https://user-images.githubusercontent.com/93697794/162516953-ec19b3cf-c910-401d-8cf8-a167ca92af3a.png">

<img width="1048" alt="Screenshot 2022-04-08 at 20 52 05" src="https://user-images.githubusercontent.com/93697794/162516960-7cb78df7-7707-443d-82f7-43a53ef75c64.png">

Not sure what to do.

I have a Mac M1 but I was even trying to make it work in Ubuntu and the same problem.

Can you help please? Thanks

**Comment by dimitrovmaksim** [comment]
Are you using pnpm?

**Comment by HetmanJones** [comment]
no, I was using docker and now using graph test only but no errors are being shown. The weird thing is that I downloaded the subgraph demo and it worked, but for this project I have the same dependencies and it doesn't work

**Comment by dimitrovmaksim** [comment]
Have you tried deleting yarn.lock/package-lock.json and `node_modules` folder and doing a clean install of the deps

**Comment by HetmanJones** [comment]
I actually found the problem, it was related with yarn workspaces, the solution was to no hoist matchstick-as

**Comment by HetmanJones** [comment]
I was already doing with the other dependencies except this one, thanks for your help !

**Comment by sebastiantf** [comment]
Seeing this error with pnpm monorepo
