### ISSUE TITLE
Add option to configure the `subgraph.yaml` location in matchstick.yaml

### ISSUE THREAD

**Issue by dimitrovmaksim** [LimeChain/matchstick#331]
We should add an option (`manifestPath: path/to/subgraph.yaml`) to configure the `subgraph.yaml` location in matchstick.yaml the same way we can currently configure the path to the tests or node_module folders. 

Where subgraph.yaml is used:
https://github.com/LimeChain/matchstick/blob/6640ac0da997193d4de562f55aa25ae443ccf47d/src/main.rs#L43
https://github.com/LimeChain/matchstick/blob/6640ac0da997193d4de562f55aa25ae443ccf47d/src/coverage.rs#L13

https://thegraph.com/docs/en/developer/matchstick/#configuration
https://github.com/LimeChain/matchstick/blob/main/src/config.rs
https://github.com/LimeChain/matchstick/blob/main/src/main.rs#L47-L48

Estimate: 2 days

**Comment by bachstatter** [comment]
Any estimate when this will be released?

**Comment by dimitrovmaksim** [comment]
It is available in version 0.5.0 https://github.com/LimeChain/matchstick/releases/tag/0.5.0
