### ISSUE TITLE
Autogenerated examples for test structures on init/add

### ISSUE THREAD

**Issue by Kalina-Todorova** [LimeChain/matchstick#353]

**Comment by dimitrovmaksim** [comment]
Подобно както init и add генерират [./src/<file-name>.ts](https://github.com/graphprotocol/graph-cli/blob/75f53a164b2aab9772a920efbe262ca87bb661ad/src/command-helpers/scaffold.js#L107), така трябва да се генерират и хелпър файл със функции за създаване на:
1. [mockEvent](https://github.com/LimeChain/demo-subgraph/blob/main/tests/gravity/utils.ts#L38-L52)-и - примерно във файл`./tests/utils.ts` както е в линка.
2. Някакъв примерен тест, примерно `./tests/<dataSource-name>.tests.ts`, който не е задължително да е точно функциониращ тест, но по-скоро да показва структурата. Примерно може да има:
  - един `describe()` за някой eventHandler, 
  - в него един `beforeAll()`, в който се генерира mockEvent и се подава на handler-а
  - след това `test()` в който се assert-ва, че от даден entity type има 1 бройка примерно
  - след това `afterAll` в който се извиква `clearStore()`. Съответно трябва и да се include-ват необходимите файлове и node_module-и. 
 3. matchstick работи само за ethereum събграфове, така че ще трябва да съобразиш тези неща да се генерират само ако protocol-a e ethereum, разгледай Protocol класа и как се използва.

**Comment by dimitrovmaksim** [comment]
Също в такъв случай ще е хубаво да се добави и matchstick-as към package.json-а като се генерира, може да видиш как се случва това при init и да добавиш да се слага и matchstick-as.
