### ISSUE TITLE
matchstick fails to find asc binary on M1 Macbook

### ISSUE THREAD

**Issue by mrod502** [LimeChain/matchstick#356]
When running `graph test` from `/Users/<user>/code/rift/rift-subgraph/rinkeby`, the following occurs:
```
💬 Compiling vault/updated_vault...
thread 'main' panicked at '🆘 Internal error during compilation: No such file or directory (os error 2).
Command path: "/Users/<user>/code/rift/rift-subgraph/rinkeby/node_modules/assemblyscript/bin/asc"
Globals path: "/Users/<user>/code/rift/rift-subgraph/rinkeby/node_modules/@graphprotocol/graph-ts/global/global.ts"
Libs folder: "/Users/<user>/code/rift/rift-subgraph/rinkeby/node_modules"', src/compiler.rs:131:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error Command failed with exit code 101.
```

In `/Users/<user>/code/rift/rift-subgraph/rinkeby/node_modules/assemblyscript/bin/`, there exist 2 files: 
 - `asc.js`
 - `asinit.js`

**Comment by dimitrovmaksim** [comment]
What package manager do you use?

**Comment by mrod502** [comment]
> Do you use yarn workspaces?
> 
> If not, you can try to delete `node_modules` folder and any lock files(yarn.lock and/or package-lock.json) and try to install the deps again

Did a clean install of dependencies, seems to have fixed the problem. Thanks!

**Comment by coreyar** [comment]
I am encountering this issue using yarn workspaces.

**Comment by dimitrovmaksim** [comment]
You can also try to configure the node_modules folder which matchstick should use with https://thegraph.com/docs/en/developing/unit-testing-framework/#configuration
