### ISSUE TITLE
Can't find node_modules if it is not in the same level as matchstick.yaml file

### ISSUE THREAD

**Issue by fritzschoff** [LimeChain/matchstick#378]
This error will get thrown when he can't find the node_modules folder.
`thread 'main' panicked at '🆘 Path to lib "./node_modules" does not exist!', src/compiler/mod.rs:37:13`
I'm in a monorepo where the node modules folder is in the root. But since my tests are in a package sub dir, I can't run these tests. 
Can the matchstick.yaml file be extended to provide a custom path to the node modules folder?

**Comment by dimitrovmaksim** [comment]
The point of the matchstick.yaml file is to configure any of the paths to point to other locations. You should be able to configure like this `libsFolder: ../../path/to/node_modules`

**Comment by fritzschoff** [comment]
Ah okay. Misunderstood the libsFolder key. Thanks

**Comment by dimitrovmaksim** [comment]
If they yaml file does not exist or a key is not set, the path will default to the ones specified in the readme
