### ISSUE TITLE
Matchstick attempts to download "undefined" version

### ISSUE THREAD

**Issue by FlacoJones** [LimeChain/matchstick#379]
Matchstick version: `"matchstick-as": "^0.5.4"`

After running `yarn test`, matchstick attempts to download a binary with `undefined` in the path

`https://github.com/LimeChain/matchstick/releases/download/undefined/binary-macos-11` returns a 404

it should be `https://github.com/LimeChain/matchstick/releases/download/0.5.4/binary-macos-11`

```
(base) ~/OpenQ-Fullstack/OpenQ-Graph > yarn test
yarn run v1.22.17
warning ../../package.json: No license field
$ graph test
Fetching latest version tag
Downloading release from https://github.com/LimeChain/matchstick/releases/download/undefined/binary-macos-11
Error fetching release: Request failed with status code 404
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by dimitrovmaksim** [comment]
This sometimes happen due github api issues. Try again with `yarn test -f` once to force a redownload

**Comment by dimitrovmaksim** [comment]
Graph cli caches the request for the latest version for 24 hours, you can force it with the `-f` flag
