### ISSUE TITLE
Running only one test at a time for development

### ISSUE THREAD

**Issue by hasparus** [LimeChain/matchstick#388]
It would be nice to be able to run just one test at a time to help focus and minimize clutter in the output during debugging.

There are two approaches to this, `test.only` or specifying test name in the command args either by string or regex.

Examples:

- [`test.only() in Vitest`](https://vitest.dev/api/#test-only)
- [`cargo test [name]`](https://doc.rust-lang.org/rust-by-example/testing/unit_testing.html#running-specific-tests)

**Comment by dimitrovmaksim** [comment]
Hey there 👋🏻 , this is something that's been on our list too. We will look into it, but as we have mentioned in other issues, it may take some time due to other priority higher tasks we have on our hands right now.

**Comment by hasparus** [comment]
@dimitrovmaksim Would you accept an external PR that adds this?

**Comment by dimitrovmaksim** [comment]
Hey @hasparus, all contributions are welcome. We are planing some changes to the repos and want to start fresh, that's why I'm closing all issues here.
