### ISSUE TITLE
Make recent versions available for package managers

### ISSUE THREAD

**Issue by rolandsaven** [LimeChain/matchstick#389]
Hey there,

It would be nice to have `0.5.3` and `0.5.4` available for yarn and npm.

It's currently at [0.5.2](https://www.npmjs.com/package/matchstick-as/v/0.5.2)

Thanks! 🙏

**Comment by dimitrovmaksim** [comment]
Hey, `matchstick-as` (from the link) is the helper library (similarly to graph-ts for graph-cli) which provides the helper functions (test, describe, createMockedFunction, etc). Its most recent version is `0.5.2`. Matchstick (this repo) on the other hand is the tool runs the tests, similarly to how `graph-node` runs the subgraphs. It is downloaded automatically when running the `graph test` command and unless specified with `graph test -v 0.5.2` it should always fetcht he latest version which is `0.5.4`.
