### ISSUE TITLE
[Suggestion] Add verbose to assert fails

### ISSUE THREAD

**Issue by OscBacon** [LimeChain/matchstick#395]
Hi, first off, great testing library!
It would be nice to have more verbose on assert fails. As of right now, I have to add log statements to find out which assert exactly failed.

For example, on a series `assert.entityCount`, this message is not helpful enough:
```
X𝖷 (assert.equals) Expected value was '1' but actual value was '0'
```
(and the backtrace doesn't say much)

Secondly, having assert functions with a message field could help too, a la nodejs assert: https://nodejs.org/api/assert.html

If I understand correctly, AS doesn't allow for function overloading or optional arguments. One solution could be to have an `assert` namespace, and an `assertMessage` namespace with the same functions, but that throw a custom message when the assert fails

**Comment by dimitrovmaksim** [comment]
Hey @OscBacon, `matchstick` version `0.6.0-beta3` and `matchstick-as` version `0.6.0-beta.0` are now available, which add optional 3rd argument `message` to each assert function. You can try them now. `matchstick` `0.6.0-beta3` should also be backwards compatible with `matchstick-as` `0.5.2`. Keep in mind also that this is a beta and also includes fixes for derived fields for entities with Bytes Id's and `log.critical` interrupting the tests execution, so there could be some bugs and issues in general.

**Comment by OscBacon** [comment]
Looks promising!

**Comment by dimitrovmaksim** [comment]
Should be resolved by https://github.com/LimeChain/matchstick/pull/408, can be tested with https://github.com/LimeChain/matchstick/releases/tag/0.6.0-rc.3
