### ISSUE TITLE
Entity loadInBlock not working

### ISSUE THREAD

**Issue by Louis-Amas** [LimeChain/matchstick#396]
I think the title is self explanatory :)

I'm using auto generated code with graph codegen
```
thread 'main' panicked at '🆘 Could not create WasmInstance from valid module with context: unknown import: `index::store.get_in_block` has not been defined'
```

**Comment by dimitrovmaksim** [comment]
Hey, I believe this is new functionality that was added recently, so it's not implemented in matchstick.

**Comment by Louis-Amas** [comment]
Ok, I think it should be easy to add as we can just create a function load_in_block that fallback to normal load ?

**Comment by Preston-Harrison** [comment]
Same with `loadRelated`

**Comment by dimitrovmaksim** [comment]
Should be fixed by https://github.com/LimeChain/matchstick/pull/398 and https://github.com/LimeChain/matchstick/pull/399
Can be tested with https://github.com/LimeChain/matchstick/releases/tag/0.6.0-rc.3
