### ISSUE TITLE
Error: thread 'main' panicked at ':sos: Internal error during compilation: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by nour-karoui** [LimeChain/matchstick#428]
I want to test my subgraph with **_matchstick-as_** and the **_@graphprotocol_** libraries. For the package manager I am using **_pnpm_**. 
Here is the list of my dependencies:
```
devDependencies:{
    "@graphprotocol/graph-cli": "^0.73.0",
    "@graphprotocol/graph-ts": "^0.35.1",
    "matchstick-as": "^0.6.0",
}
```
When I run `graph test` I get this error:
`thread 'main' panicked at ':sos: Internal error during compilation: No such file or directory (os error 2).`
However, this works fine when I use _**npm**_

<img width="1074" alt="image" src="https://github.com/LimeChain/matchstick/assets/47257753/6b024489-27fe-4469-8047-5fcd995d57c9">

**Comment by dimitrovmaksim** [comment]
For pnpm, try adding `"assemblyscript": "^0.19.20"` to the devDependencies

**Comment by nour-karoui** [comment]
I tried with `"assemblyscript": "^0.19.23"` and it fixed my issue thank you very much
